while getopts 'n:' flag; do
  case "${flag}" in
    n) iter_num="${OPTARG}" ;;
    *)
      echo "Usage: $0 [-n iter_num]"
      exit 1
      ;;
  esac
done
iter_num_last=$((${iter_num} - 1))
wb_command -metric-math '(x0+x1+x2+x3+x4+x5+x6+x7+x8+x9+x10+x11+x12+x13+x14+x15+x16)/17' /HPC_work_dir/corrdice_affine_mask/checkNODE2078_msmrefine/NODE2078_${iter_num}.curv.affine.ico6.shape.gii -var x0 /HPC_work_dir/corrdice_affine_mask/checkNODE2078_msmrefine/119025.R.MSM.NODE2078_${iter_num}.transformed_and_reprojected.func.gii -var x1 /HPC_work_dir/corrdice_affine_mask/checkNODE2078_msmrefine/156536.R.MSM.NODE2078_${iter_num}.transformed_and_reprojected.func.gii -var x2 /HPC_work_dir/corrdice_affine_mask/checkNODE2078_msmrefine/386250.R.MSM.NODE2078_${iter_num}.transformed_and_reprojected.func.gii -var x3 /HPC_work_dir/corrdice_affine_mask/checkNODE2078_msmrefine/208327.L.MSM.NODE2078_${iter_num}.transformed_and_reprojected.func.gii -var x4 /HPC_work_dir/corrdice_affine_mask/checkNODE2078_msmrefine/208327.R.MSM.NODE2078_${iter_num}.transformed_and_reprojected.func.gii -var x5 /HPC_work_dir/corrdice_affine_mask/checkNODE2078_msmrefine/206929.L.MSM.NODE2078_${iter_num}.transformed_and_reprojected.func.gii -var x6 /HPC_work_dir/corrdice_affine_mask/checkNODE2078_msmrefine/156233.R.MSM.NODE2078_${iter_num}.transformed_and_reprojected.func.gii -var x7 /HPC_work_dir/corrdice_affine_mask/checkNODE2078_msmrefine/214726.R.MSM.NODE2078_${iter_num}.transformed_and_reprojected.func.gii -var x8 /HPC_work_dir/corrdice_affine_mask/checkNODE2078_msmrefine/727654.R.MSM.NODE2078_${iter_num}.transformed_and_reprojected.func.gii -var x9 /HPC_work_dir/corrdice_affine_mask/checkNODE2078_msmrefine/165032.R.MSM.NODE2078_${iter_num}.transformed_and_reprojected.func.gii -var x10 /HPC_work_dir/corrdice_affine_mask/checkNODE2078_msmrefine/973770.R.MSM.NODE2078_${iter_num}.transformed_and_reprojected.func.gii -var x11 /HPC_work_dir/corrdice_affine_mask/checkNODE2078_msmrefine/381543.R.MSM.NODE2078_${iter_num}.transformed_and_reprojected.func.gii -var x12 /HPC_work_dir/corrdice_affine_mask/checkNODE2078_msmrefine/815247.R.MSM.NODE2078_${iter_num}.transformed_and_reprojected.func.gii -var x13 /HPC_work_dir/corrdice_affine_mask/checkNODE2078_msmrefine/124220.L.MSM.NODE2078_${iter_num}.transformed_and_reprojected.func.gii -var x14 /HPC_work_dir/corrdice_affine_mask/checkNODE2078_msmrefine/351938.L.MSM.NODE2078_${iter_num}.transformed_and_reprojected.func.gii -var x15 /HPC_work_dir/corrdice_affine_mask/checkNODE2078_msmrefine/365343.L.MSM.NODE2078_${iter_num}.transformed_and_reprojected.func.gii -var x16 /HPC_work_dir/corrdice_affine_mask/checkNODE2078_msmrefine/237334.R.MSM.NODE2078_${iter_num}.transformed_and_reprojected.func.gii;
wb_command -metric-math 'abs(x-y)' /HPC_work_dir/corrdice_affine_mask/checkNODE2078_msmrefine/difference.shape.gii -var x /HPC_work_dir/corrdice_affine_mask/checkNODE2078_msmrefine/NODE2078_${iter_num_last}.curv.affine.ico6.shape.gii -var y /HPC_work_dir/corrdice_affine_mask/checkNODE2078_msmrefine/NODE2078_${iter_num}.curv.affine.ico6.shape.gii;
diff=$(wb_command -metric-stats /HPC_work_dir/corrdice_affine_mask/checkNODE2078_msmrefine/difference.shape.gii -reduce MEAN -roi /HPC_work_dir/frontal_lobe/rotated_deformed_frontal_lobe_corrdice/NODE2078_frontal_mask.shape.gii);
echo $diff;

cp /HPC_work_dir/corrdice_affine_mask/checkNODE2078_msmrefine/NODE2078_${iter_num}.curv.affine.ico6.shape.gii /HPC_work_dir/corrdice_affine_mask/checkNODE2078_msmrefine/NODE2078.final.curv.affine.ico6.shape.gii
